# Generated by Django 3.0.5 on 2020-04-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upfile',
            name='file',
            field=models.FileField(upload_to='upload/%Y/'),
        ),
    ]
